config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'tasks#index'

  resources :tasks
  resources :sharings, only: :create
  
  get 'index' => 'tasks#index', as: :index

end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :user_tasks
  has_many :users, :through => :user_tasks 

  validates_presence_of [:title, :description] 

  def shared_to(user)
    shared_by = user.user_tasks.find_by(task_id: id).andand.shared_by_id
    User.find_by_id(shared_by)
  end

  def share(from_user, to_user)
    UserTask.create user_id: to_user.id, task_id: id, shared_by_id: from_user.id
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :user_tasks
  has_many :tasks, :through => :user_tasks 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def full_name
    [first_name, last_name].join(' ')
  end

  # def share(task, to_user)
  #   UserTask.create user_id: to_user.id, task_id: task.id, shared_by_id: self.id
  # end

end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  belongs_to :shared_by, class: 'User'

  validates_uniqueness_of :task_id, :scope => :user_id

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
    def record_not_found
      render plain: "404 Not Found", status: 404
    end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sharings_controller.rb
class SharingsController < ApplicationController
  before_action :authenticate_user!

  def create
    if to_user = User.find_by_email(sharing_params[:email])
      task.share current_user, to_user
      flash[:alert] = "Task was successfully shared to #{to_user.full_name}"
      redirect_to root_path
    else
      flash[:alert] = "User with such email not exist"
      redirect_to root_path
    end
  end

  private
    def sharing_params
      params.require(:sharing).permit(:email, :task_id) if params[:sharing]
    end 

    def task
      @task ||= current_user.tasks.find(sharing_params[:task_id])
    end
    helper_method :task
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    if request.xhr?
      render :partial => "table"
    end
  end

  def show
  end

  def new
    @resource = Task.new
  end

  def edit
  end

  def create
    @resource = Task.new(task_params)
    resource.users << current_user
    resource.save ? redirect_to(resource, notice: 'Task was successfully created.') : render(:new)
  end

  def update
    respond_to do |format|
      format.html do 
        if resource.update(task_params) 
          redirect_to(resource, notice: 'Task was successfully updated.') 
        else
          render(:edit)
        end
      end
      format.json { render json: { success: resource.update(task_params) } }
    end
  end

  def destroy
    resource.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.' 
  end

  private
    def resource
      @resource ||= current_user.tasks.find(params[:id])
    end
    helper_method :resource

    def resources
      @resources ||= current_user.tasks
    end
    helper_method :resources

    def task_params
      params.require(:task).permit(:title, :description, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sharings_helper.rb
module SharingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ToDo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/sharings/new.html.haml
.modal.hide.fade{:id => "modal-window", :role => "dialog", "aria-labelledb" => "myModalLabel", "aria-hidden" => "true"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3.modal-title 
      = 'Share to "' +  @task.title + '" task'
  .modal-body
    = form_for :user do |f|
      = f.email_field :email 
      = f.submit 'Share', :class => 'btn btn-primary'
    .ajax-loader
  .modal-footer
    %button.btn{"data-dismiss" => "modal", :type => "button"} close

app/views/tasks/_form.html.haml
= form_for resource, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_field :description, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), 
      tasks_path, :class => 'btn'                                  

app/views/tasks/_modal.html.haml
.modal.hide.fade{:id => "modal-window-#{resource.id}", :role => "dialog", "aria-labelledb" => "myModalLabel", "aria-hidden" => "true"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3.modal-title 
      = 'Share to "' +  resource.title + '" task'
  .modal-body
    = form_for :sharing, url: sharings_path do |f|
      = f.email_field :email 
      = f.hidden_field :task_id, value: resource.id 
      = f.submit 'Share', :class => 'btn btn-primary'
    .ajax-loader
  .modal-footer
    %button.btn{"data-dismiss" => "modal", :type => "button"} close

app/views/tasks/_table.html.haml
- model_class = Task
- model_subclass = UserTask
%table.table.table-striped
  %thead
    %tr
      %th Status
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_subclass.human_attribute_name(:shared_by)
      %th= model_class.human_attribute_name(:title)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - resources.each do |task|
      %tr
        %td
          = check_box_tag 'done', task.id , task.done, :class => "task-check"

        %td= task.description
        %td= task.created_at.strftime('%d/%m/%Y %H:%M:%S')
        %td
          - if shared_by = task.shared_to(current_user)
            = shared_by.full_name 
        %td= task.title
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), 
            edit_task_path(task),
            :class => 'btn btn-mini'

          = link_to 'Invite', '#', class: 'btn btn-mini', 
            remote: true,
            'data-toggle' =>  "modal",
            'data-target' => "#modal-window-#{task.id}"
        
          = link_to t('.destroy', :default => t("helpers.links.destroy")),
            task_path(task),
            method: :delete,
            data:  { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, 
            class: 'btn btn-mini btn-danger'
          = render 'modal', resource: task

app/views/tasks/edit.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tasks/index.html.haml
%ul.nav.nav-pills.pull-right
  - if user_signed_in? 
    Logged in as |
    = link_to "#{current_user.email}.", edit_user_registration_path, :class => 'navbar-link'
    = link_to 'Log out', destroy_user_session_url, :method => :delete 
  - else 
    = link_to "Sign up", new_user_registration_path, :class => 'navbar-link' |
    = link_to "Login", new_user_session_path, :class => 'navbar-link'


.page-header
  %script{:type=>"text/javascript"}
    setInterval(updateTable, 4000);
  %h1= 'My tasks'
- if flash[:alert]
  .alert 
    = flash.now[:alert]

#tasks-list 
  = render :partial => "table"

= link_to t('.new', :default => t("helpers.links.new")), 
  new_task_path,
  class: 'btn btn-primary'

app/views/tasks/new.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/tasks/show.html.haml
- model_class = Task
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:title)
      \:
  %dd= resource.title
  %dt
    %strong
      = model_class.human_attribute_name(:description)
      \:
  %dd= resource.description
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), |
    tasks_path, :class => 'btn'                              |
  -#
  = link_to t('.edit', :default => t("helpers.links.edit")), |
    edit_task_path(resource), :class => 'btn'                |
  -#
  = link_to t('.destroy', :default => t("helpers.links.destroy")),                                               |
    task_path(resource),                                                                                         |
    :method => 'delete',                                                                                         |
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, |
    :class => 'btn btn-danger'                                                                                   |